.github/workflows/c-cpp.yml
.gitignore
Makefile
Makefile.emscripten

- Adds two CI entries (osx + linux) for running `mhs` tests via `node` and comparing outputs
- Adds `Makefile.emscripten` in the top-level directory (invoked using `make emscripten` from `Makefile`)
- `git` ignores some stuff
- Doesn't bother to compile the compiler to JS or WASM
- Doesn't contain tests for WASM (could be added later w/ `wasmer`)
- Some tests didn't pass `Foreign`, `Floating`, (so just commented them for now -- failures described below)
- Doesn't use `mhseval` for any of the tests
- `Foreign`
```
TypeError: Cannot convert -5 to a BigInt
```
- `Floating`
```
2c2
< -1.0
---
> 0.9938211910561482
```
^ still looking into these
- Wasn't immediately obvious how to cleanly reuse `tests/Makefile` w/ `emcc`, but that would be an improvement to avoid some code duplication.
- …

Adds emscripten Makefile and CI entries

---

Tools/Addcombs.hs
src/runtime/eval.c

This avoids a segfault when compiling via `.comb` files.

Match the output format of `mhs -ofoo.c`. 

---

src/runtime/eval.c

This opens the door to topologically sorting the list of bindings and squashing even more indirections.  Or, dare I say it, tree-shaking the bindings and avoiding all those A combinators.  (There are debugging reasons why that might not be a great plan, see eg https://github.com/augustss/MicroHs/pull/23)

Don't create indirections for unreferenced labels during deserialization

---

src/runtime/config-unix-64.h
src/runtime/eval.c

I decided to run sanitzers on this and found why I was getting periodic heap corruption – it was tmpname overflowing its buffer.  But it's ubsan I'm interested in as I'm screwing around with eval and gc a bit and trying not to confuse the optimizer.

Fix asan and ubsan violations, one of which was causing periodic crashes

---

README.md

- the old make `install` target is now called `oldinstall`
- the new make `installmcabal` target is now `install`

readme: update install targets

---

Makefile

Use "echo -e" to enable interpreting the backslash escapes.

Fix Paths_MicroHs

---

lib/Data/Ord.hs

I stumbled across the fact that the function `clamp` is missing in `Data.Ord`. If there is a reason why the function is not implemented, please let me know and simply close the PR.

Implement `clamp` in Data.Ord

---

lib/Data/Integer.hs
lib/Data/Integer_Type.hs
lib/Data/Word.hs

Some small optimizations for `Integer`s. Each optimization is in its own commit:
* Since each digit is nonnegative, we can use `Word` instead of `Int` to represent digits. This allows us to use half of the bits (16/32) without multiplication overflow. It also has the effect that any `Int` and `Word` can be represented using at most 2 digits.
* Since `maxD` is a power of 2, we can use bit operations instead of `quot` and `rem` (see `quotMaxD`, `remMaxD`).
* `dropWhileEnd (== 0)` seems to be a bit more efficient than `reverse . dropWhile (== 0) . reverse`.
* `quotRemI` used to traverse `ys` 4 times in the case that all digits except the MSD are 0: once for `init`, `last`, `length` and `all`. `msd` does all this in a single traversal.
* ~~`_integerToIntList` and `_intListToInteger` used …

Optimize `Integer` a bit

---

lib/Data/Bits.hs
lib/Data/Int/Instances.hs
lib/Data/Word.hs

In C, shifting by a negative number or a number greater than or equal to the number of bits is UB. `shiftL` and `shiftR` now guard against this. Also uncomment the `Bits` instances for `Int8`, `Int16`, `Int32` and `Int64` and add `FiniteBits` instances.

Fix UB in shifts & add missing `Bits` instances

---

lib/Data/Bits.hs
lib/Data/Int/Instances.hs
lib/Data/Integer.hs
lib/Data/Integer_Type.hs
lib/Data/Word.hs

Implement the `Bits Integer` instance and add `bitDefault`, `testBitDefault` and `popCountDefault` to `Data.Bits` (these are copied from `base`). Also readd the optimizations reverted in https://github.com/augustss/MicroHs/commit/2ec34c1ab7655acce61166bd267290b590e20a1a (most of that didn't even use `Data.Bits` in the first place).
The `Bits Integer` instance works like in `base`, by pretending that negative numbers are stored in 2's complement (so that they conceptually have an infinite number of leading ones).
I wrote a script to generate some test cases using `QuickCheck`, which I then ran with MicroHs (I had to use `gmhs`, since `mhs` took too long).

Implement `Bits Integer` instance

---

lib/Data/Integer.hs
lib/Data/Integer/Internal.hs

Compare `Integer`s using a single traversal of the digits, rather than computing the lengths and reversing the lists first.

Integer: Optimize comparisons

---

lib/Data/List.hs

Since they used `foldl`/`foldr`, they were not actually strict. I also tried the versions used in `base` (using `foldl` for `foldr'` and `foldr` for `foldl'`), but they were worse in my micro-benchmark (I ran `print $ foldl' (+) 0 [1..10_000::Int]`/`print $ foldr' (+) 0 [1..10_000::Int]` and checked the number of reductions and memory usage), although the alternative `foldl'` actually uses less memory.

Fix strictness of `foldl'` & `foldr'`

---

lib/Control/Exception.hs

I don't see any reason why they're not exported.

Export `evaluate` and `mapException` from `Control.Exception`

---

lib/Data/List.hs
lib/Data/List_Type.hs

Changes:
* better instances
- implement `Ord [a]` by defining `compare` instead of `<=`
- define `*>`, `liftA2` in the `Applicative []` instance
- define `stimes` in the `Semigroup [a]` instance
* optimizations
- ~~define `length` the naive way, in my micro-benchmark (`print $ length [1..10_000::Int]`) this was a lot better (taking 2/3 of the reductions)~~
- optimize `span`, `spanUntil`, `splitWith`, `inits` to avoid `reverse`
- optimize `partition`, `unsnoc` to use a single traversal
- use merge sort for sorting (see #74)
- inline `combine` in `transpose`
- add shortcuts for empty lists in `intersectBy`
- slightly better `unlines`, `unwords` (using the `base` versions)
* avoid helpers for functions that are optimized anyway (`concatMap`, `map`, `filter`, `foldr`, `foldr1`, `foldr1'`, …

`Data.List` improvements

---

README.md
lib/gmp/Data/Integer/Internal.hs
src/MicroHs/FFI.hs
src/runtime/eval.c

* For `shiftR`, we want `mpz_fdiv_q_2exp` (rounding down towards -infinity) instead of `mpz_tdiv_q_2exp` (rounding towards zero). E.g. ``(-1 :: Integer) `shiftR` 1 == -1``.
* For `popCount` on negative integers, we want -1 times the popcount of the absolute value, so I added code to negate the input and output in case the input is negative.

Fix GMP `popCount` & `shiftR`

---

lib/Data/String.hs
tests/StringTest.hs
tests/StringTest.ref

Change to `instance (a ~ Char) => IsString [a]`, so that the string type can be inferred if it is known to be a list (e.g. in `length "hello"`). This is also in `base`, see https://hackage.haskell.org/package/ghc-internal-9.1201.0/docs/src/GHC.Internal.Data.String.html#line-63.

Better `IsString` instance for `String`

---

.gitignore
.gitmodules
Makefile

Use git submodule instead of git clone for fetching cpphs. This is better for reproducability as cpphs may change in a MicroHs incompatible way in the future.

Switch to git submodule for cpphs

---

.gitignore
.gitmodules
Makefile

Reverts augustss/MicroHs#106
I like the this in principle, but it doesn't work.
```
augustss@Lennarts-MBP MicroHs % make bootstrapcpphs
git submodule update --init --depth 1 cpphssrc/malcolm-wallace-universe
error: pathspec 'cpphssrc/malcolm-wallace-universe' did not match any file(s) known to git
make: *** [cpphssrc/malcolm-wallace-universe/.git] Error 1
```

Revert "Switch to git submodule for cpphs"

---

Makefile

Running `make clean` deletes the cpphs submodule (and git tracks that as a change). Use `git submodule deinit` to properly clean cpphs.

Fix make clean and have git deinit the cpp submodule

---

lib/Data/ByteString.hs
lib/Data/ByteString/Internal.hs
src/MicroHs/Translate.hs
src/runtime/eval.c

Add `bsindex` primitive for indexing into a `ByteString` in O(1) and use it to implement `head`, `tail`, `index` and `indexMaybe`.

Add `bsindex` primitive

---

README.md

Earlier, I was confused about the purpose of the patches. I assumed that they where just needed to actually get Hugs to compile, as unpatched Hugs from https://www.haskell.org/hugs/ doesn't compile with modern C compilers. This disambiguate whey they're needed.

Edit README to explain why a patched version of Hugs is needed

---

lib/Text/Printf.hs

Make it possible to use `Double` with  `printf`. Is there any reason why it was commented out?

Uncomment `PrintfArg Double` instance

---

hugs/PrimTable.hs
hugs/System/IO/Serialize.hs

Make the error messages when bootstrapping with hugs actually show "hugs" instead of "ghc" ;)

Fix hugs error messages

---

lib/Data/Integer_Type.hs

We always want half the word size as `shiftD`. With this change, `Integer` should also work on e.g. 16 bit platforms.

Integer: simplify `shiftD` computation

---

src/runtime/bfile.c

They were missing a `FREE` call.

Fix memory leak in `encode_bwt` & `decode_bwt`

---

src/runtime/config-unix-64.h
src/runtime/eval.c

This is a small fix that allows MicroHs to be compiled with the Tiny C Compiler.
`tcc` was chocking on `#elif defined(__clang__) && __has_builtin(...)`. Instead, `__has_builtin` is now guarded as is recommended by the GCC manual: https://gcc.gnu.org/onlinedocs/cpp/_005f_005fhas_005fbuiltin.html.

Fix to allow compilation with Tiny C Compiler

---

src/MicroHs/Parse.hs
src/MicroHs/TargetConfig.hs
src/Text/ParserComb.hs

Optimize the parser by making it deterministic (i.e. allow at most one success). This is done in several steps:
- Step 1 (cd2ad121950a2cbf1ac9bc5299333cd5388f5fa8): Replace all uses of `<|>` (including transitive uses in `many`, `some`, etc.) by `<|<`, preserving the semantics by possibly changing the order in which the parsers are combined.
- Step 2 (ddad212cd930202f7a15f2af420153674593f0ee): Change the `Prsr` definition to allow at most one success. This removes the possibility of "Ambiguous" errors.
- Step 3 (58dedada0a40b26925e6e21cdca7db3b2eb861d9): Change all uses of `<|<` to `<|>`, which now has the same behaviour.
Overall, these changes make compiling mhs use 2.6% less memory and run 2.1% faster (measured using `bin/mhs -ipaths -imhs -isrc MicroHs.Main +RTS -v`).
As an experiment, …

Optimize parser

---

src/MicroHs/Builtin.hs
src/MicroHs/Compile.hs
src/MicroHs/SymTab.hs

Only `pack` `"B@"`/`"Mhs.Builtin"` once. This slightly improves performance (~0.01%).

Small optimization in `MicroHs.Builtin`

---

lib/Data/Bits.hs
lib/Data/Int/Instances.hs
lib/Data/Integer.hs
lib/Data/Word.hs
lib/Numeric/Natural.hs

Bits.isSigned is defined in Haskell 2010 and is present in GHC base.
(From https://github.com/augustss/MicroHs/pull/166#issuecomment-2708965073)

Add isSigned to class Bits

---

.github/workflows/mhs-ci.yml

Run `make newmhs` before running the emscripten tests, to avoids failures like https://github.com/augustss/MicroHs/pull/155#issuecomment-2701373378.

Make emscripten CI less fragile

---

src/runtime/eval.c

when skipping full regions, and using standard bit fiddling to mark as used.  This offers a nice (and repeatable) speedup on my MacBook Pro.  It should be a LOT better on any arch that lacks native FFS support.
(Note: I've deleted the GC stats because they're the same between runs)
Baseline (master):
2ad52978fc17d361f43a9e47f708935d0853df41
time bin/mhs +RTS -v -RTS -s -i  -imhs -isrc -ilib -ipaths  MicroHs.Main 1940 lines/s
24.40 real        23.59 user         0.22 sys
time bin/mhs +RTS -v -RTS -CW AllOfLib
20.47 real        19.73 user         0.16 sys
time bin/mhs +RTS -v -RTS -CR -s -i  -imhs -isrc -ilib -ipaths  MicroHs.Main
4339 lines/s
16.34 real        15.94 user         0.18 sys
With FFS avoidance and faster mark_used in alloc_node: 2ad52978fc17d361f43a9e47f708935d0853df41
time …

Speed up node allocation noticeably by avoiding FFS(...)

---

src/runtime/eval.c

This yields a fast branch-free path when reduction creates a pair of spine ap nodes.  A tiny change that's worth 3.5%-4% vs trunk but should have no real concerns.
user+sy stddev	user	stddev	sys	stddev	user+sy	        user		sys
ap2	cached	15.017	0.346	14.863	0.333	0.154	0.024	4.24%		4.20%		7.88%
ap2	full	22.436	0.537	22.245	0.507	0.191	0.053	3.90%		3.93%		0.60%
ap2	libs	19.711	0.396	19.521	0.373	0.190	0.036	3.55%		3.57%		1.04%
master	cached	15.681	0.406	15.514	0.378	0.167	0.039	0		0		0
master	full	23.347	0.531	23.155	0.500	0.192	0.041	0		0		0
master	libs	20.436	0.458	20.243	0.429	0.192	0.041	0		0		0

Fast path for two aps

---

src/MicroHs/ExpPrint.hs
tests/Bytestring.hs
tests/Bytestring.ref

The `IsString ByteString` instance truncates the `Char`s to `Word8`s. `ByteString` literals assumed that the `Char`s were already truncated, leading to a compiler crash when using Unicode `ByteString` literals.

Fix compiler error with Unicode ByteString literals

---

lib/Foreign/Marshal.hs
lib/Foreign/Marshal/Error.hs

The report specifies `Foreign.Marshal.Error.void` to have type `IO a -> IO ()`, whereas this PR reexports `Data.Functor.void` (which has type `Functor f => f a -> f ()`). I can change it to strictly adhere to the report, but ig this is good enough. For the record, `base` has a separate `void :: IO a -> IO ()`, but it's deprecated (in favor of `Data.Functor.void`).

Make `Foreign.Marshal` & `Foreign.Marshal.Error` report compliant

---

src/runtime/eval.c

sprintf makes sanitized builds justifiably unhappy.  This is a trivial fix, especially as eval.c already calls snprintf in convdbl.

sprintf -> snprintf

---

src/runtime/eval.c

Combinator names on master are assigned based on the *last* thing we see that matches the combinator.  This leads to unintuitive stuff like:
> cprint id
chr
By reversing the order of name assignment, we favor combinator names over primitives that happen to be spelled the same way.

Fix combinator naming

---

src/runtime/eval.c

According to a comment the less than combinator is defined as Z B, but it clearly is Z K

Fixed incorrect and confusing comment

---

.github/workflows/mhs-ci.yml

Combine `build-linux-emscripten` and `build-macos-emscripten` into a single job using a matrix strategy.

Simplify emscripten CI

---

MicroHs.cabal

This PR contains the following changes:
- adding a library section to the MicroHs.cabal file
- removing the MicroCabal folder as Cabal complains about an empty submodule..

Exposing MicroHs as a library to make it reusable in external projects

---

.gitignore
tests/Makefile

Update `.gitignore` with
- `*.hi-boot`, `*.o-boot` (generated by GHC since https://github.com/augustss/MicroHs/commit/4937c9803e349c033db424629c3e4c18802ee23b where `src/MicroHs/TCMonad.hs-boot` was added)
- `tests/*.exe`, `tests/.so` (generated by tests)
and update `make clean` to remove `tests/*.so` files.

Update `.gitignore` & `make clean`

---

lib/Numeric.hs
lib/Numeric/FormatFloat.hs
lib/Numeric/Read.hs
lib/Numeric/Show.hs

Make `Numeric` report compliant by exporting more functions that were already there and newly defining `readFloat` and `fromRat`. The `readFloat` code is taken verbatim from GHC base, the `fromRat` implementation is adapted from the GHC version. `Numeric` now imports `Prelude`, since I didn't want to write down all the needed imports, I hope that's okay .

Make `Numeric` report compliant

---

lib/gmp/Data/Integer_Type.hs
src/MicroHs/FFI.hs
src/runtime/eval.c
tests/Integer.hs

`mpz_get_ui` ignores the sign, so it gets the least significant bits of the absolute value, which is not the behaviour we want. Instead, I modified `mpz_get_si` to properly handle `maxBound :: Int`.
Similarly, I changed `mpz_get_si64` to use the code of `mpz_get_ui64`, with the small change to use `mpz_tdiv_q_2exp` (logical right shift) instead of `mpz_fdiv_q_2exp` (arithmetic right shift), to get the absolute value (which is then negated if the input was negative).
`mpz_init_set_si64` was also broken for negative values, so I changed it to use `mpz_init_set_ui64` and negate the result if the input was negative.

Fix GMP conversion functions

---

lib/Data/Complex.hs

- Add a `Read` instance, based on what GHC would generate (since deriving wouldn't produce the correct instance yet)
- Fix the `Show` instance to consider precedence
- Add an export list
- Uncomment the `**` definition
- Use literal patterns (I assume the reason they were commented out is that they weren't supported when the module was added?)
With these changes, `Data.Complex` is (more or less report) compliant. Technically, the report has a `RealFloat a =>` datatype context, so every instance also requires that (and the `Show` instance doesn't require `Show a`). However, datatype contexts are widely considered a misfeature; they're deprecated in GHC and MicroHs doesn't support them at all. GHC just derives `Read` and `Show` (which generates the instances I added), so we should be good.

Make `Data.Complex` (more or less) report compliant

---

.hlint.yaml
lib/Data/Complex.hs
src/MicroHs/Deriving.hs
src/MicroHs/Desugar.hs
src/MicroHs/Expr.hs
src/MicroHs/Fixity.hs
src/MicroHs/Parse.hs
src/MicroHs/TypeCheck.hs
tests/Deriving.hs
tests/Deriving.ref

For this, I modified the parser to allow backticked constructors and fixed `pUOper`, which previously allows patterns like ``a `(,)` b = 42``. `Constr` now has a `(Ident, Bool)`, where the `Bool` indicates whether the constructor was written in infix notation. This is currently ignored in `ppConstr`.

Consider whether constructors were written in infix notation when deriving `Show`/`Read`

---

lib/Foreign/C/Types.hs

The instances are not entirely correct, since they don't respect the sizes of the C types. This also applies to the other derived instances.

Add `Bits` & `FiniteBits` instances for C types

---

lib/Data/Fractional.hs
lib/Data/Function.hs
lib/Prelude.hs

Add missing `Prelude` exports and missing fixity declarations.
With these changes, `Prelude` is almost report compliant. The only thing that's missing is `catch :: IO a -> (IOError -> IO a) -> IO a`, which is called `catchIOError` in MicroHs and GHC (`catch` also exists, but has a more general type). However, GHC doesn't export `catch` (or `catchIOError`) from `Prelude` either, so this is consistent with GHC.

Add missing `Prelude` exports

---

.github/workflows/hackage-ci.yml

`split` and `monad-loops` both have no dependencies apart from `base`, are pretty popular, and build with MicroHs out of the box. Let's make sure that it stays that way!

Build more packages in CI

---

.github/workflows/hackage-ci.yml

After https://github.com/ekmett/tagged/pull/69, `tagged` compiles with MicroHs. It has a lot of reverse dependencies (both direct and indirect), so this is a good step to get more packages to compile with MicroHs.

Add `tagged` to Hackage CI
